### ISSUE TITLE
Dragging is not working 

### ISSUE THREAD

**Issue by vinayakb-pits** [SmallStoneSK/react-native-draggable-calendar#1]
I install the demo example on nexus 5. But multiple date selection not working(by dragging). But I can select a single date.  a period selection not working. I downloaded directly from GitHub. Please ping me if you want more details

**Comment by SmallStoneSK** [comment]
@vinayakb-pits have you ever changed another simulator or phone and have a try?

**Comment by vinayakb-pits** [comment]
Yeah. I tried it on Moto G5sPlus also. But selecting a period by dragging is not working (Android version 7.1.1)

**Comment by SmallStoneSK** [comment]
@vinayakb-pits Sorry for that.  I've found the error. As I use UIManager.measure to get the layout of elements, it always return 0 for x and y on Android (https://github.com/facebook/react-native/issues/4753). And I've changed another function UIManager.measureLayout to fix this bug. You can update the version to 1.0.1 and try it again.

**Comment by vinayakb-pits** [comment]
@SmallStoneSK It's working perfectly. Thank you so much
