### ISSUE TITLE
[Bug] TypeError: Invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by some-say** [SmallStoneSK/react-native-draggable-calendar#2]
Hello, i found bug

<img width="554" alt="error" src="https://user-images.githubusercontent.com/7961070/46089755-7cadc280-c1af-11e8-8c1e-55f4132012cc.png">

change line react-native-draggable-calendar/src/Day.js:35
to 
`
if (data && data.status) {
  usedDayContainerStyle.push(...containerStyleMap[data.status]);
}
`

**Comment by SmallStoneSK** [comment]
@some-say Can you show the case how this bug happens? As each DayItem's data must contain a status attribute, which is a type of enum value (DAY_STATUS), it ensures that containerStyleMap[data.status] is an array.
