### ISSUE TITLE
Enhancement - Is it possible to select multiple date range in single calendar view?

### ISSUE THREAD

**Issue by vinayakb-pits** [SmallStoneSK/react-native-draggable-calendar#3]
Selecting a single date range is working perfectly. Is there any roadmap for selecting multiple date range from a single calendar view?

**Comment by SmallStoneSK** [comment]
@vinayakb-pits Thank you for your suggestion. Actually, I ever considered this. However, it is a complex operation as many details should be dealt. For example, if you want to select multiple date range, how to clear the selected date range? For current version, if you select a new date  range, selected range will be cleared.

**Comment by vinayakb-pits** [comment]
@SmallStoneSK My suggestion is clicking again on the same selected range will clear the selection, and clicking another date will be a new date range. I know It's too complicated workflow. anyway, I will also try to do this.  Thanks for your reply and support. This library is awesome.

**Comment by ribas14** [comment]
Maybe it would be possible to create a new component on top of the first one, set the background and other stuff to transparent, and alternate the components between clicks to change the zindex of the next component.

**Comment by SmallStoneSK** [comment]
> Maybe it would be possible to create a new component on top of the first one, set the background and other stuff to transparent, and alternate the components between clicks to change the zindex of the next component.

@ribas14 so how to clear the selected components? If you have this need, I can have a try.
